// Sample entries for every section of the band and the /inbox pane, shown by
// `/inbox demo` for work on the layout. Nothing here reaches the session's
// real inbox, its store, or Claude.

import type { Checks, Ledger, PrViews, Settled, Stop } from '../types'

export type View = { ledger: Ledger; stop: Stop | null; checks: Checks; settled: Settled[]; prViews: PrViews }

const MIN = 60_000
const REPO = 'https://github.com/petekp/inbox'

export function demoView(now: number): View {
  return {
    ledger: {
      card: {
        goal: 'Give the inbox pane keyboard shortcuts and a cleaner tab bar',
        done: ['Tabs switch with 1, 2 and 3', 'Answer keys moved to letters', 'PR #31 opened'],
        now: 'Waiting on where the Keys list goes and a gh sign-in',
        running: ['live test session: tmux attach -t inbox-live'],
        updatedAt: now - 2 * MIN,
      },
      items: [
        {
          id: 'd11',
          kind: 'decide',
          label: '1',
          ask: 'Show the Keys list in a footer, or under the tab bar?',
          options: ['Footer', 'Under the tab bar'],
          rec: 'Footer',
          helps: [],
          turn: 14,
          at: now - 12 * MIN,
        },
        {
          id: 'd12',
          kind: 'decide',
          label: '2',
          ask: 'Keep findings open until you confirm a fix?',
          options: ['Keep it open', 'Close it'],
          rec: 'Keep it open',
          helps: [],
          turn: 14,
          at: now - 12 * MIN,
        },
        {
          id: 'd13',
          kind: 'decide',
          label: '3',
          ask: 'Expire questions after 20 prompts, not 12?',
          options: ['Yes', 'No'],
          rec: 'No',
          helps: [],
          turn: 14,
          at: now - 12 * MIN,
        },
        {
          id: 'd14',
          kind: 'do',
          label: null,
          ask: 'Sign in to gh for the PRs tab',
          options: [],
          rec: null,
          helps: [{ kind: 'terminal', command: 'gh auth login', name: 'gh auth login' }],
          turn: 14,
          at: now - 5 * MIN,
        },
        {
          id: 'd15',
          kind: 'decide',
          label: null,
          ask: 'Which theme should the README screenshot use?',
          options: [],
          rec: null,
          helps: [],
          turn: 11,
          at: now - 40 * MIN,
        },
        {
          id: 'd16',
          kind: 'do',
          label: null,
          ask: 'Check the pane in the light theme',
          options: [],
          rec: null,
          helps: [{ kind: 'copy', text: '/theme', name: 'theme command' }],
          turn: 14,
          at: now - 5 * MIN,
        },
        {
          id: 'd17',
          kind: 'do',
          label: null,
          ask: 'Run /reload-plugins in your other sessions',
          options: [],
          rec: null,
          helps: [],
          turn: 12,
          at: now - 25 * MIN,
        },
      ],
      decided: [
        {
          id: 'd5',
          kind: 'decide',
          ask: 'Rename the Waiting tab?',
          outcome: 'Needs you',
          how: 'answered',
          at: now - 90 * MIN,
        },
        {
          id: 'd6',
          kind: 'decide',
          ask: 'Commit the reload fix and the rename as two commits?',
          outcome: 'yes',
          how: 'answered',
          at: now - 60 * MIN,
        },
        {
          id: 'd9',
          kind: 'do',
          ask: 'Update Claude Code to 2.1.292',
          outcome: 'done',
          how: 'done',
          at: now - 45 * MIN,
        },
        {
          id: 'd7',
          kind: 'decide',
          ask: 'Keep the darker body behind the section cards?',
          outcome: 'closed by Claude: no longer applies: the body matches the tab bar',
          how: 'claude',
          at: now - 30 * MIN,
        },
        {
          id: 'd8',
          kind: 'decide',
          ask: 'Add a fourth Session tab?',
          outcome: 'dismissed',
          how: 'dismissed',
          at: now - 20 * MIN,
        },
        {
          id: 'd10',
          kind: 'decide',
          ask: 'Draw the tabs on the pane’s own background?',
          outcome: 'Yes, as part of the title bar',
          how: 'answered',
          at: now,
        },
      ],
      findings: [
        {
          id: 'd20',
          kind: 'opportunity',
          title: 'One contrast check could cover all six themes',
          detail:
            'A capture of the pane in each theme holds every cell’s colors. A script could flag any text under 4.5:1 and run in check.sh.',
          path: 'scripts/check.sh',
          at: now - 3 * 60 * MIN,
        },
        {
          id: 'd21',
          kind: 'opportunity',
          title: 'Catch-up could read only the turns it missed',
          detail:
            'After a reload, the catch-up call reads the whole conversation. Starting from the last turn the ledger applied would cut its tokens on long sessions.',
          path: 'hooks/ledger.ts',
          at: now - 90 * MIN,
        },
        {
          id: 'd22',
          kind: 'issue',
          title: 'Hotkeys vanish on selected rows in ANSI',
          detail:
            'The engine draws hotkeys in the same blue the selected row uses as its background, so a: and b: disappear there.',
          path: 'hooks/register.tsx',
          at: now - 45 * MIN,
        },
        {
          id: 'd23',
          kind: 'issue',
          title: 'Selected tab is unreadable in dark ANSI',
          detail:
            'The selected tab is drawn on ANSI white with the default light text. Its name needs a dark color there, or an inverse style.',
          path: 'hooks/register.tsx',
          at: now - 30 * MIN,
        },
      ],
      prs: ['petekp/inbox#31', 'petekp/inbox#29', 'petekp/inbox#33'],
      nextId: 24,
      turn: 14,
      batchTurn: 14,
    },
    stop: null,
    checks: {
      results: [
        {
          name: 'prettier',
          kind: 'lint',
          folder: null,
          result: 'pass',
          summary: '',
          ranAt: now - 20 * MIN,
          command: 'npx -y prettier@3.9.9 --check .',
          failures: [],
          repo: null,
          isStale: true,
          isLeftFailing: false,
          isDismissed: false,
        },
        {
          name: 'claude plugin test',
          kind: 'tests',
          folder: null,
          result: 'pass',
          summary: '64 pass, 0 fail',
          ranAt: now - 6 * MIN,
          command: 'claude plugin test .',
          failures: [],
          repo: null,
          isStale: false,
          isLeftFailing: false,
          isDismissed: false,
        },
        {
          name: 'tsc',
          kind: 'types',
          folder: null,
          result: 'fail',
          summary: 'hooks/register.tsx(2310,7): error TS2322',
          ranAt: now - 5 * MIN,
          command: 'npx -y -p typescript tsc --noEmit -p .',
          failures: [
            "hooks/register.tsx(2310,7): error TS2322: Type 'string | undefined' is not assignable to type 'string'.",
          ],
          repo: null,
          isStale: false,
          isLeftFailing: true,
          isDismissed: false,
        },
        {
          name: 'claude plugin validate',
          kind: 'validate',
          folder: null,
          result: 'unknown',
          summary: '',
          ranAt: now - 4 * MIN,
          command: 'claude plugin validate .',
          failures: [],
          repo: null,
          isStale: false,
          isLeftFailing: false,
          isDismissed: false,
        },
      ],
    },
    settled: [
      {
        id: 'd10',
        ask: 'Draw the tabs on the pane’s own background?',
        outcome: 'Yes, as part of the title bar',
        how: 'answered',
        at: now,
        kind: 'decide',
        index: 1,
      },
    ],
    prViews: {
      branchRef: 'petekp/inbox#31',
      isFetching: false,
      views: {
        'petekp/inbox#31': {
          ref: 'petekp/inbox#31',
          number: 31,
          title: 'Switch tabs with 1, 2 and 3, and letter the answers',
          url: `${REPO}/pull/31`,
          isDraft: false,
          state: 'OPEN',
          base: 'main',
          mergeable: 'MERGEABLE',
          reviewDecision: 'CHANGES_REQUESTED',
          checks: [
            { name: 'prettier', bucket: 'pass', url: `${REPO}/actions/runs/1` },
            { name: 'plugin tests', bucket: 'fail', url: `${REPO}/actions/runs/2` },
            { name: 'plugin validate', bucket: 'pending', url: null },
          ],
          threads: [
            {
              id: 'DT1',
              author: 'sam',
              reply: null,
              isWaiting: true,
              isOutdated: false,
              path: 'hooks/register.tsx',
              line: 1147,
              body: 'Why do the answer keys skip d? A question has no Done action.',
              replies: 0,
              url: `${REPO}/pull/31#discussion_r1`,
            },
            {
              id: 'DT2',
              author: 'sam',
              reply: {
                author: 'robin',
                body: 'Agreed, the footer reads better than a list under the tabs.',
                url: `${REPO}/pull/31#discussion_r3`,
              },
              isWaiting: true,
              isOutdated: true,
              path: 'README.md',
              line: 87,
              body: 'Should the Keys list live in the footer?',
              replies: 1,
              url: `${REPO}/pull/31#discussion_r2`,
            },
            {
              id: 'DT3',
              author: 'robin',
              reply: { author: 'you', body: 'Done in the latest push.', url: `${REPO}/pull/31#discussion_r5` },
              isWaiting: false,
              isOutdated: false,
              path: 'hooks/register.tsx',
              line: 2296,
              body: 'Can the tab width come from the label alone now?',
              replies: 1,
              url: `${REPO}/pull/31#discussion_r4`,
            },
          ],
          fetchedAt: now - MIN,
          error: null,
        },
        'petekp/inbox#29': {
          ref: 'petekp/inbox#29',
          number: 29,
          title: 'Count turns to tell when a reload cut off an update',
          url: `${REPO}/pull/29`,
          isDraft: false,
          state: 'OPEN',
          base: 'main',
          mergeable: 'MERGEABLE',
          reviewDecision: 'APPROVED',
          checks: [
            { name: 'prettier', bucket: 'pass', url: null },
            { name: 'plugin tests', bucket: 'pass', url: null },
          ],
          threads: [],
          fetchedAt: now - MIN,
          error: null,
        },
        'petekp/inbox#33': {
          ref: 'petekp/inbox#33',
          number: 33,
          title: 'Draw the tabs on the pane’s own background',
          url: `${REPO}/pull/33`,
          isDraft: true,
          state: 'OPEN',
          base: 'main',
          mergeable: 'MERGEABLE',
          reviewDecision: '',
          checks: [
            { name: 'prettier', bucket: 'pass', url: null },
            { name: 'plugin tests', bucket: 'pending', url: null },
          ],
          threads: [],
          fetchedAt: now - MIN,
          error: null,
        },
      },
    },
  }
}
